# Generated by Django 2.2.4 on 2020-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='How_Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='image/how_use')),
            ],
        ),
        migrations.CreateModel(
            name='How_Use_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='image/products_img')),
                ('preco_one', models.CharField(max_length=60, null=True)),
                ('por_div', models.CharField(max_length=60, null=True)),
                ('prize_div', models.CharField(max_length=80, null=True)),
                ('buy_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecDashImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=100, null=True)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='image/how_use')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('details', models.TextField()),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('details', models.TextField(null=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='principal.Ingredients')),
            ],
        ),
    ]
